### ISSUE TITLE
Heroku Review Apps を設定する

### ISSUE THREAD

**Issue by takeyuweb** [takeyuwebinc/sample-feedreader-rails#11]
Pull-Request ごとにHeroku環境を自動で作ってくれるすごい機能があるようです。
これ超便利そうなので、

https://qiita.com/kon_yu/items/6d2c0ae91d0176ceb167

こちらを参考に作ってみていただけますか？

**Comment by itkrt2y** [comment]
kon_yuさんの記事なら信用はできるけど、基本公式ドキュメントを見て対応してほしい
https://devcenter.heroku.com/articles/github-integration-review-apps
