### ISSUE TITLE
PR時に自動でテストを行うようにする

### ISSUE THREAD

**Issue by takeyuweb** [takeyuwebinc/sample-feedreader-rails#12]
いま、PRを作成すると、以下が自動実行されるようになっています。

- SideCI コード上のあやしいところを指摘してくれる
- Heroku Review Apps レビュー用の動作テスト用アプリ環境を作ってくれる

加えて、 #10 で作ったテストを自動的に実行してくれるようにしてみましょう。

## 課題

CircleCI 2.0 の設定をしてみる

## 達成すべき目標

Pull-Requestしたとき、CircleCI でテストが実行されて、結果がPull-Requestに表示される

![image](https://user-images.githubusercontent.com/60980/37336526-0000810a-26f5-11e8-8844-8190039f0316.png)

## 何がうれしいか？

- レビュー者が自分の環境でテストを動かさなくても、それをパスすることを確認できる
- 時間のかかるテストの場合、自分の環境で動かさなくてもシステムに任せることができる
- テストを通す癖がつき、壊れたまま放置されることを防ぐ

など、レビュー者にもプロジェクトにもやさしいしくみ

## CIツールについて

CircleCIのほかに、SideCI、本プロジェクトでは使用していないが、TravisCI、Jenkinsなどのツールがある。

くわしくは継続的インテグレーション Continuous Integration でググってください。

**Comment by shiraryu** [comment]
@takeyuweb 承知しました！取り組んでいきます！
