### ISSUE TITLE
Herokuに載せる

### ISSUE THREAD

**Issue by takeyuweb** [takeyuwebinc/sample-feedreader-rails#2]
RSSフィードから情報を抜き出して一覧表示するアプリをHeroku上で動くようにして見せてください。

- [x] Heroku について調べる
- [x] Heroku を試してみる
- [x] Automatic deploy を設定してみる

ことを通してPaaSの基礎知識とHerokuというサービスの存在・基礎について学習してもらうのが目的です。

**Comment by takeyuweb** [comment]
@shiraryu 次はこちらをやってみて、動いているところを見せてください。

**Comment by shiraryu** [comment]
@takeyuweb 承知しました！お昼以降に取り掛かっていきます！

**Comment by shiraryu** [comment]
@takeyuweb 
一旦、Herokuへのアップを行いました。一度ご確認ください。

https://pure-sands-30178.herokuapp.com/feeds

**Comment by takeyuweb** [comment]
OKです

**Comment by takeyuweb** [comment]
@shiraryu Herokuのautomatic deploy機能を有効にすると、GitHub上でmasterが更新されたとき、自動でアプリを更新することができるようになります。

https://devcenter.heroku.com/articles/github-integration#automatic-deploys

↓[takeyuweb-rails](https://github.com/takeyuwebinc/takeyuweb-rails)では以下のように設定することで、PRがマージされたら https://takeyuweb.co.jp に反映されるようにしています。

![image](https://user-images.githubusercontent.com/60980/37337138-c0b00884-26f6-11e8-8c2f-f13e3e191db4.png)

この設定を行うことで、たとえば、 #10 がマージされたところで、

https://pure-sands-30178.herokuapp.com

に反映されるようになります。

（実際には `db:migrate` は手動で行わないといけなかった気がしますが…

**Comment by shiraryu** [comment]
@takeyuweb 設定していきます！

**Comment by shiraryu** [comment]
@takeyuweb 設定完了しました！（master選択、「Wait fo CI....」にチェックを入れて）

**Comment by takeyuweb** [comment]
@shiraryu これで次からはmergeされたら自動で反映されますね。

ただその前に、 https://pure-sands-30178.herokuapp.com でここまでの最新をみたいので、手動デプロイを試してみてくださいますか。

![image](https://user-images.githubusercontent.com/60980/37377259-289ecee2-276c-11e8-8bd8-8a3f73aa3c62.png)

https://devcenter.heroku.com/articles/getting-started-with-rails4#deploy-your-application-to-heroku

**Comment by shiraryu** [comment]
@takeyuweb  一旦、手動デプロイを行いました。ご確認をお願いします！

**Comment by takeyuweb** [comment]
@shiraryu OKです :+1:
